Repository TULbaghia/ZZPJ-Project, pull requests merged in 2021-06, with the labels that each got.

#14 Part of GH-3 performance tweaks
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/controller/ArticleController.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/controller/QuestionController.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/dto/WordDto.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/manager/ArticleService.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/manager/ArticleWordService.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/manager/TopicService.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/manager/WordService.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/repository/ArticleRepository.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/repository/ArticleWordRepository.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/repository/TopicRepository.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/repository/WordRepository.java
Labels: enhancement

#16 Implement Questionnaire services
  src/main/java/pl/lodz/p/it/zzpj/exception/AccessDeniedException.java
  src/main/java/pl/lodz/p/it/zzpj/exception/QuestionnaireException.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/controller/QuestionnaireController.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/dto/QuestionnaireDto.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/dto/QuestionnaireQuestionDto.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/manager/QuestionService.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/manager/QuestionnaireService.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/mapper/IQuestionnaireMapper.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/repository/QuestionnaireQuestionRepository.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/repository/QuestionnaireRepository.java
Labels: enhancement

#19 EmailSender removed, token expiration time changed #17
  src/main/java/pl/lodz/p/it/zzpj/email/EmailSender.java
  src/main/java/pl/lodz/p/it/zzpj/email/EmailService.java
  src/main/java/pl/lodz/p/it/zzpj/service/auth/controller/AccountController.java
  src/main/java/pl/lodz/p/it/zzpj/service/auth/manager/RegistrationService.java
  src/main/resources/application.yml
Labels: invalid

#23 Implement QuestionService tests
  src/test/java/pl/lodz/p/it/zzpj/ZzpjApplicationTests.java
  src/test/java/pl/lodz/p/it/zzpj/thesis/manager/QuestionService_AllowedWords.java
  src/test/java/pl/lodz/p/it/zzpj/thesis/manager/QuestionService_EpochTests.java
  src/test/java/pl/lodz/p/it/zzpj/thesis/manager/QuestionService_WordsByArticles.java
  src/test/java/pl/lodz/p/it/zzpj/thesis/utils/ThesisFilterTests.java
  src/test/resources/drop_all.sql
  src/test/resources/init_question_service.sql
Labels: enhancement

#20 Access configuration
  src/main/java/pl/lodz/p/it/zzpj/service/auth/security/config/WebSecurityConfig.java
Labels: enhancement

#25 Fix small issues, Add exception mappings
  src/main/java/pl/lodz/p/it/zzpj/entity/questionnaire/Questionnaire.java
  src/main/java/pl/lodz/p/it/zzpj/exception/AccessDeniedException.java
  src/main/java/pl/lodz/p/it/zzpj/exception/ApiException.java
  src/main/java/pl/lodz/p/it/zzpj/exception/AppBaseException.java
  src/main/java/pl/lodz/p/it/zzpj/exception/NoRecordsException.java
  src/main/java/pl/lodz/p/it/zzpj/exception/QuestionnaireException.java
  src/main/java/pl/lodz/p/it/zzpj/exception/RegistrationException.java
  src/main/java/pl/lodz/p/it/zzpj/exception/WordException.java
  src/main/java/pl/lodz/p/it/zzpj/exception/mapper/ExceptionMapper.java
  src/main/java/pl/lodz/p/it/zzpj/service/auth/security/config/WebSecurityConfig.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/controller/QuestionnaireController.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/dto/QuestionnaireDto.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/dto/QuestionnaireQuestionDto.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/manager/QuestionService.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/manager/QuestionnaireService.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/mapper/IQuestionnaireMapper.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/api/TranslationApi.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/controller/ArticleController.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/controller/TopicController.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/dto/FetchArticleDto.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/dto/TopicDto.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/dto/WordDto.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/dto/internal/ArticleDto.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/dto/internal/ArticleListDto.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/manager/ArticleWordService.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/manager/TopicService.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/mapper/IArticleMapper.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/mapper/ITopicMapper.java
  src/test/java/pl/lodz/p/it/zzpj/thesis/manager/QuestionService_EpochTests.java
Labels: bug, enhancement

#28 Handle token exception and loggers added
  src/main/java/pl/lodz/p/it/zzpj/service/auth/manager/AccountService.java
  src/main/java/pl/lodz/p/it/zzpj/service/auth/manager/RegistrationService.java
  src/main/java/pl/lodz/p/it/zzpj/service/auth/security/config/WebSecurityConfig.java
  src/main/java/pl/lodz/p/it/zzpj/service/auth/security/jwt/JwtAuthenticationFilter.java
  src/main/java/pl/lodz/p/it/zzpj/service/auth/security/jwt/JwtTokenVerifier.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/manager/QuestionnaireService.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/api/NatureApi.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/api/TranslationApi.java
Labels: bug

#30 Uzupełnienie testów dla Questionnaire oraz pakietu thesis
  src/main/java/pl/lodz/p/it/zzpj/entity/thesis/Article.java
  src/main/java/pl/lodz/p/it/zzpj/exception/QuestionnaireException.java
  src/main/java/pl/lodz/p/it/zzpj/exception/TopicException.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/controller/QuestionnaireController.java
  src/main/java/pl/lodz/p/it/zzpj/service/questionnaire/manager/QuestionnaireService.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/api/TranslationApi.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/controller/ArticleController.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/controller/TopicController.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/manager/ArticleService.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/manager/ArticleWordService.java
  src/main/java/pl/lodz/p/it/zzpj/service/thesis/manager/TopicService.java
  src/test/java/pl/lodz/p/it/zzpj/TestSecurityContext.java
  src/test/java/pl/lodz/p/it/zzpj/ZzpjApplicationTests.java
  src/test/java/pl/lodz/p/it/zzpj/questionnaire/manager/QuestionServiceAllowedWordsTests.java
  src/test/java/pl/lodz/p/it/zzpj/questionnaire/manager/QuestionServiceEpochTests.java
  src/test/java/pl/lodz/p/it/zzpj/questionnaire/manager/QuestionServiceWordsByArticlesTests.java
  src/test/java/pl/lodz/p/it/zzpj/questionnaire/manager/QuestionnaireServiceTests.java
  src/test/java/pl/lodz/p/it/zzpj/thesis/manager/ArticleServiceTests.java
  src/test/java/pl/lodz/p/it/zzpj/thesis/manager/ArticleWordServiceTests.java
  src/test/resources/application.yml
Labels: enhancement
